spring:
  application:
    name: kube-land

  datasource:
    url: jdbc:mysql://mysql:3306/kube_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  tracing:
    sampling:
      probability: 1.0  # Temporar setează la 100% pentru testare
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


param:
  land-name: kube-land
  land-service: kube-land
  microserv1-name: kube-ms1
  microserv1-service: kube-ms1
  api-service: api-service
  auth-service-name: kube-auth
  auth-service: kube-auth
  notifications-name: kube-notifications
  notifications-service: notification-service
