spring:
  application:
    name: kube-land

  datasource:
    url: jdbc:mysql://localhost:3306/kube_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true
    show-sql: true

  security:
    jwt:
      - expiration-time: 3600000
      - secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

token:
  signing:
    key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"

cors:
  allowed-origin: ${ADDITIONAL_CORS_ORIGIN:http://localhost:3000}
param:
  land-name: kube-land
  land-service: localhost
  microserv1-name: kube-ms1
  microserv1-service: localhost
  api-service: localhost


server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8082



#spring.security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#  # 1h in millisecond
#  security.jwt.expiration-time=3600000