spring:
  application:
    name: kube-land

  datasource:
    url: jdbc:mysql://localhost:3306/kube_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    show-sql: true

  security:
    jwt:
      - expiration-time: 3600000
      - secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

token:
  signing:
    key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"

cors:
  allowed-origin: ${ADDITIONAL_CORS_ORIGIN:http://localhost:3000,http://localhost:8082,http://react-app.local,http://react-app:3000,http://react-app.local:3000,http://icode.mywire.org,http://icode.mywire.org:3000}
param:
  land-name: kube-land
  land-service: localhost
  microserv1-name: kube-ms1
  microserv1-service: localhost
  api-service: localhost

springdoc:
  api-docs:
    enabled: true  # Activează OpenAPI JSON
  swagger-ui:
    enabled: true  # Activează Swagger UI
    path: /swagger-ui.html  # Calea unde poate fi accesat Swagger
    operations-sorter: method  # Sortează endpoint-urile după metoda HTTP
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0  # Temporar setează la 100% pentru testare
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: debug
  file:
    name: kube-land-logs.log


#spring.security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#  # 1h in millisecond
#  security.jwt.expiration-time=3600000